### ISSUE TITLE
日時、場所文字変更、地図情報添付

### ISSUE THREAD

**Issue by yasuyasu2022** [yasuyasu2022/iniad-fake-homepage#1]
文字サイズをもう少し大きくする
色は黒色
場所のキャンプ明日をクリックするとキャンパスMAPが表示される

**Comment by yasuyasu2022** [comment]
檜山さん、本件どうぞよろしくお願いいたします。

**Comment by hiyakou** [comment]
ご連絡ありがとうございます。作成次第、ご報告させていただきます。

**Comment by hiyakou** [comment]
対応しましたので、クローズさせていただきます。
