### ISSUE TITLE
文字の大きさや色のルール決め

### ISSUE THREAD

**Issue by shimizu-yuki-a11y** [yasuyasu2022/iniad-fake-homepage#3]
●文字の色
基本黒をベース
URL付きの文字の色は青　など

●文字のサイズ
見出し、大項目、小項目ごとにフォントサイズを決める

**Comment by yasuyasu2022** [comment]
ジョシュアさん、本件よろしくお願いします。

**Comment by yasuyasu2022** [comment]
ジョシュアさんに代わり安岡が担当させていただきます。

**Comment by yasuyasu2022** [comment]
文字色を黒ベースに、文字サイズ調整、スケジュールの背景と枠を調整しました。
このissueは一旦完了とします。

**Comment by yasuyasu2022** [comment]
作業完了しました。
