### ISSUE TITLE
画像を追加する

### ISSUE THREAD

**Issue by hiyakou** [yasuyasu2022/iniad-fake-homepage#4]
INIADのロゴを追加する。
項目ごとに追加してもいいと思う。（例：学びを知ろう→ 講義中のイラストor写真など）

**Comment by yasuyasu2022** [comment]
多田さん、本件よろしくお願いいたします。

**Comment by citydx2022-017** [comment]
日本語と英語のindex.htmlファイルにINIADのロゴを追加してみました。

**Comment by citydx2022-017** [comment]
完了しました。
